host: localhost
port: 10000

skills:
    -   id: retrieve_medical_data
        name: Trợ lý y tế
        description: Tìm kiếm dữ liệu trong lĩnh vực y tế để trả lời câu hỏi cho người dùng
        tags:
            - medical
            - retriever
        examples:
            - Đau đau là do nguyên nhân nào gây ra?
            - Có thể là do virus hay do cảm lạnh?
            - Trong mùa mưa mình thường mắc bệnh gì?
            - Những căn bệnh thông dụng thường thấy trong cuộc sống là gì?


card:
    name: Trợ lý y tế
    description: Đây là một trợ lỹ hữu ích, giúp người dùng tìm kiếm dữ liệu riêng của công ty trong lĩnh vực y tế và phản hồi lại cho người dùng
    version: 1.0.0

# agent
retriever_system:
    type: ensemble
    retrievers:
        -   type: rephrase
        -   type: multiple_query
        # -   type: contextual_compression
        #     compressor:
        #         type: rerank
    weights:
        -   0.5
        -   0.5
        # -   0.5

retriever_tool:
    name: medical_retriever
    description: Công cụ hữu ích trong việc tìm kiếm thông tin về sức khoẻ, y tế, bệnh thông dụng trong tài liệu liên quan.

SYSTEM_INSTRUCTIONS: 
    - Bạn là một trợ lý hữu ích trong lĩnh vực y tế và sức khoẻ.
    - Nếu câu trả lời nằm ngoài phạm vi y tế và nội dung được cho, hãy trả lời không biết, không được tạo ra câu trả lời khác.