embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  model_kwargs: 
    device: 'cpu'
  encode_kwargs:
    normalize_embeddings: False


chunk_size: 512
chunk_overlap: 128
data_source_path: ./data/active
vectorstore_path: ./vectorstore/data