
model:
  model_id: google/gemma-3-4b-it

model_params:
  temperature: 0.1
  max_tokens: Null
  timeout: Null
  max_retries: 2

embedding:
  model_name: caliex/all-MiniLM-L6-v2-f16.gguf

server:
  base_url: http://localhost:8000/v1

retrieval:
  search_kwargs:
    k: 10

data_source: ../data/source

vector_db:
  chunk_size: 512
  chunk_overlap: 64
